apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  labels:
    app: MY-application
spec:
  replicas: 3
  selector:
    matchLabels:
      app: MY-application
  template:
    metadata:
      labels:
        app: MY-application
    spec:
      containers:
        - name: my-app-container
          image: docker.io/ahmedmaher07/itsys
          ports:
            - containerPort: 8082

---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: MY-application
  ports:
    - protocol: TCP
      port: 8082  
      targetPort: 8082  
  type: NodePort
