    - name: Update APT package list
      apt:
        update_cache: yes

    - name: Install required dependencies
      apt:
        name:
          - gnupg2
          - curl
          - software-properties-common
        state: present

    - name: Add Grafana GPG key
      apt_key:
        url: https://packages.grafana.com/gpg.key
        state: present

    - name: Add Grafana APT repository
      apt_repository:
        repo: "deb https://packages.grafana.com/oss/deb stable main"
        state: present
        filename: grafana

    - name: Update APT package list after adding Grafana repo
      apt:
        update_cache: yes

    - name: Install Grafana
      apt:
        name: grafana
        state: present

    - name: Enable and start Grafana service
      systemd:
        name: grafana-server
        enabled: yes
        state: started

    - name: Ensure Grafana is running on port 3000
      wait_for:
        port: 3000
        timeout: 30
        state: started
