
# Update APT repositories and cache
- name: Run sudo apt update
  become: true
  command: apt update
  register: update_result
  changed_when: "'Hit' not in update_result.stdout"
  tags:
    - update


- name: Install Git
  apt:
    name: git
    state: present
