    - name: Add system users
      user:
        name: "{{ item.name }}"
        shell: /bin/false
        create_home: no
      loop:
        - { name: prometheus }
        - { name: node_exporter }
        - { name: alertmanager }

    - name: Create configuration directories
      file:
        path: "{{ item }}"
        state: directory
        owner: prometheus
        group: prometheus
        mode: '0755'
      loop:
        - /etc/prometheus
        - /var/lib/prometheus
        - /etc/alertmanager

    - name: Download and extract Prometheus
      unarchive:
        src: https://github.com/prometheus/prometheus/releases/download/v2.52.0/prometheus-2.52.0.linux-amd64.tar.gz
        dest: /tmp/
        remote_src: yes

    - name: Move Prometheus files
      command: mv /tmp/prometheus-2.52.0.linux-amd64/{{ item }} /etc/prometheus/
      with_items:
        - consoles
        - console_libraries
        - prometheus.yml
      ignore_errors: yes

    - name: Set ownership for Prometheus directories
      file:
        path: /etc/prometheus
        state: directory
        owner: prometheus
        group: prometheus
        recurse: yes

    - name: Move Prometheus binaries
      command: mv /tmp/prometheus-2.52.0.linux-amd64/{{ item }} /usr/local/bin/
      with_items:
        - prometheus
        - promtool

    - name: Create Prometheus systemd service file
      copy:
        dest: /etc/systemd/system/prometheus.service
        content: |
          [Unit]
          Description=Prometheus
          Wants=network-online.target
          After=network-online.target

          [Service]
          User=prometheus
          Group=prometheus
          Type=simple
          ExecStart=/usr/local/bin/prometheus \
          --config.file /etc/prometheus/prometheus.yml \
          --storage.tsdb.path /var/lib/prometheus/ \
          --web.console.templates=/etc/prometheus/consoles \
          --web.console.libraries=/etc/prometheus/console_libraries

          [Install]
          WantedBy=multi-user.target

    - name: Create Prometheus config file
      copy:
        dest: /etc/prometheus/prometheus.yml
        content: |
          global:
            scrape_interval: 15s
          rule_files:
            - "/etc/prometheus/rules.yml"
          alerting:
            alertmanagers:
              - static_configs:
                  - targets: ["localhost:9093"]
          scrape_configs:
            - job_name: 'prometheus'
              static_configs:
                - targets: ["localhost:9090"]
            - job_name: 'node_exporter'
              static_configs:
                - targets: ['localhost:9100']
            - job_name: 'docker'
              static_configs:
                - targets: ['localhost:9323']
            - job_name: 'cadvisor'
              static_configs:
                - targets: ['localhost:8080']

    - name: Create Prometheus rules file
      copy:
        dest: /etc/prometheus/rules.yml
        content: |
          {% raw %}
          groups:
            - name: cpu_alerts
              rules:
                - alert: HighCPUUsage
                  expr: 100 - (avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
                  for: 2m
                  labels:
                    severity: warning
                  annotations:
                    summary: "High CPU usage detected on {{ $labels.instance }}"
                    description: "CPU usage is above 80% for more than 2 minutes on instance {{ $labels.instance }}"
          {% endraw %}

    - name: Restart Prometheus service
      systemd:
        name: prometheus
        state: restarted

    # Install and Configure Node Exporter
    - name: Download Node Exporter
      unarchive:
        src: https://github.com/prometheus/node_exporter/releases/download/v1.7.0/node_exporter-1.7.0.linux-amd64.tar.gz
        dest: /tmp/
        remote_src: yes

    - name: Move Node Exporter binary
      command: mv /tmp/node_exporter-1.7.0.linux-amd64/node_exporter /usr/local/bin/

    - name: Set permissions for Node Exporter
      file:
        path: /usr/local/bin/node_exporter
        owner: node_exporter
        group: node_exporter
        mode: '0755'

    - name: Create Node Exporter systemd service
      copy:
        dest: /etc/systemd/system/node_exporter.service
        content: |
          [Unit]
          Description=Node Exporter
          Wants=network-online.target
          After=network-online.target

          [Service]
          User=node_exporter
          Group=node_exporter
          Type=simple
          ExecStart=/usr/local/bin/node_exporter

          [Install]
          WantedBy=multi-user.target

    - name: Start Node Exporter service
      systemd:
        name: node_exporter
        state: started
        enabled: yes
