- name: Install Java 11 on Ubuntu
  apt:
    name: openjdk-11-jdk
    state: present
    update_cache: yes

- name: Create 'jenkins' directory under /home/ubuntu
  file:
    path: /home/ubuntu/jenkins
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0755'

- name: Change permissions for /var/run/docker.sock
  file:
    path: /var/run/docker.sock
    mode: '0777'

- name: Create Kind cluster
  shell: |
    kind create cluster
  become: true

- name: Copy kube config to /home/ubuntu/
  copy:
    src: ~/.kube/
    dest: /home/ubuntu/jenkins
    remote_src: yes

- name: Start PostgreSQL
  service:
    name: postgresql
    state: started
    enabled: yes

- name: Restart PostgreSQL
  service:
    name: postgresql
    state: restarted

- name: Start Sonar
  systemd:
    name: sonar
    state: started
    enabled: yes
